name: Coverage

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/coverage.svg"

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@main
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Initializing env file
        run: |
          echo '# github action setup' >> ./contracts/.env
          echo MAINNET_URL=${{ secrets.MAINNET_URL }} >> ./contracts/.env
          echo SEPOLIA_URL=${{ secrets.SEPOLIA_URL }} >> ./contracts/.env
          echo MAINNET_FORK_BLOCK=${{ secrets.MAINNET_FORK_BLOCK }} >> ./contracts/.env
          echo PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} >> ./contracts/.env
          echo ETHERSCAN_API_KEY=${{ secrets.ETHERSCAN_API_KEY }} >> ./contracts/.env
      - name: Report coverage info in lcov.info
        run: make -C ./contracts coverage_ci
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./contracts/lcov.info
          fail_ci_if_error: true
