name: Tests

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@main
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Initializing env file
        run: |
          echo '# github action setup' >> ./contracts/.env
          echo MAINNET_URL=${{ secrets.MAINNET_URL }} >> ./contracts/.env
          echo SEPOLIA_URL=${{ secrets.SEPOLIA_URL }} >> ./contracts/.env
          echo MAINNET_FORK_BLOCK=${{ secrets.MAINNET_FORK_BLOCK }} >> ./contracts/.env
          echo PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} >> ./contracts/.env
          echo ETHERSCAN_API_KEY=${{ secrets.ETHERSCAN_API_KEY }} >> ./contracts/.env
      - name: Execute test target
        run: make -C ./contracts test

      # - name: Run coverage
      #   run: forge coverage --report lcov

      # - name: Upload coverage artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: coverage
      #     path: lcov.info
